etcd:
  image: quay.io/coreos/etcd:v2.2.0
  command: >
    -listen-client-urls http://0.0.0.0:2379
    -advertise-client-urls http://etcd:2379
monitor:
  image: caltha/akka-cluster-etcd/monitor:latest
  links:
    - "etcd:etcd"
